#!/usr/bin/env python3
"""Render README.md and img/about.svg from README.template.md in one color theme.

Switch: change THEME below and push. The workflow re-renders and commits.
Locally: python3 theme.py [blue|white|mix]
"""
import pathlib
import sys
import textwrap
from html import escape

THEME = "blue"

# heading: typing headings, card titles, card icons, about labels
# text:    card text, about body text
THEMES = {
    "blue": {"heading": "0071bc", "text": "0071bc"},
    "white": {"heading": "ffffff", "text": "ffffff"},
    "mix": {"heading": "0071bc", "text": "ffffff"},
}

ABOUT = [
    ("", "Always trying to understand and keep learning. I dip my brain into a little bit of everything "
         "to get a better understanding of how everything works around me. System administrator by day "
         "and do whatever by night."),
    ("Favorite programming language:", "Visual Basic. It was the first thing I touched, and it broke my first computer."),
    ("Interests:", "Spaceflight, Geopolitics, Gaming and Computer Science."),
]

WIDTH, SIZE, LINE, WRAP = 830, 16, 24, 105
FONT = "-apple-system, 'Segoe UI', Helvetica, Arial, sans-serif"


def about_svg(c):
    rows, y = [], SIZE
    for label, body in ABOUT:
        for i, line in enumerate(textwrap.wrap(f"{label} {body}".strip(), WRAP)):
            if i == 0 and label:
                line = f'<tspan font-weight="bold" fill="#{c["heading"]}">{escape(label)}</tspan>{escape(line[len(label):])}'
            else:
                line = escape(line)
            rows.append(f'  <text x="0" y="{y}">{line}</text>')
            y += LINE
        y += LINE // 2
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{y - LINE}" '
            f'font-family="{FONT}" font-size="{SIZE}" fill="#{c["text"]}">\n' + "\n".join(rows) + "\n</svg>\n")


def main():
    name = sys.argv[1] if len(sys.argv) > 1 else THEME
    c = THEMES[name]
    root = pathlib.Path(__file__).parent
    readme = (root / "README.template.md").read_text()
    for key, value in c.items():
        readme = readme.replace("{{" + key + "}}", value)
    assert "{{" not in readme, "unknown placeholder in README.template.md"
    (root / "README.md").write_text("<!-- Generated by theme.py from README.template.md. Edit the template. -->\n" + readme)
    (root / "img" / "about.svg").write_text(about_svg(c))
    print(f"rendered theme {name}")


if __name__ == "__main__":
    main()
